/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ActionsApi,
  AppsApi,
  AuthenticationsApi,
  ExperimentalApi,
  ZapsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { ZapierEmbedCustom } from "./client-custom";

export class ZapierEmbed extends ZapierEmbedCustom {
  readonly actions: ActionsApi;
  readonly apps: AppsApi;
  readonly authentications: AuthenticationsApi;
  readonly experimental: ExperimentalApi;
  readonly zaps: ZapsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.actions = new ActionsApi(configuration);
    this.apps = new AppsApi(configuration);
    this.authentications = new AuthenticationsApi(configuration);
    this.experimental = new ExperimentalApi(configuration);
    this.zaps = new ZapsApi(configuration);
  }

}
