/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Choice } from './choice';
import { LinksWithPage } from './links-with-page';
import { MetaWithPage } from './meta-with-page';

/**
 * 
 * @export
 * @interface ActionsGetChoicesResponse
 */
export interface ActionsGetChoicesResponse {
    /**
     * 
     * @type {Array<Choice>}
     * @memberof ActionsGetChoicesResponse
     */
    'data'?: Array<Choice>;
    /**
     * 
     * @type {MetaWithPage}
     * @memberof ActionsGetChoicesResponse
     */
    'meta'?: MetaWithPage;
    /**
     * 
     * @type {LinksWithPage}
     * @memberof ActionsGetChoicesResponse
     */
    'links'?: LinksWithPage;
}

