/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Meta } from './meta';
import { OutputField } from './output-field';

/**
 * 
 * @export
 * @interface ActionsGetOutputFieldsResponse
 */
export interface ActionsGetOutputFieldsResponse {
    /**
     * 
     * @type {Meta}
     * @memberof ActionsGetOutputFieldsResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Array<OutputField>}
     * @memberof ActionsGetOutputFieldsResponse
     */
    'data'?: Array<OutputField>;
}

