/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActionsGetChoicesRequestData } from './actions-get-choices-request-data';

/**
 * 
 * @export
 * @interface ActionsGetChoicesRequest
 */
export interface ActionsGetChoicesRequest {
    /**
     * 
     * @type {ActionsGetChoicesRequestData}
     * @memberof ActionsGetChoicesRequest
     */
    'data': ActionsGetChoicesRequestData;
}

