/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface ActionsTestActionExecution200Response
 */
export interface ActionsTestActionExecution200Response {
    /**
     * 
     * @type {Array<object>}
     * @memberof ActionsTestActionExecution200Response
     */
    'data'?: Array<object>;
    /**
     * 
     * @type {Meta}
     * @memberof ActionsTestActionExecution200Response
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Links}
     * @memberof ActionsTestActionExecution200Response
     */
    'links'?: Links;
}

