/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActionApp } from './action-app';

/**
 * An Action is an operation that can be performed against a third-party API; either a read or a write. A Zap is composed of a read, followed by one or more writes.
 * @export
 * @interface Action
 */
export interface Action {
    /**
     * The title of this Action.
     * @type {string}
     * @memberof Action
     */
    'title': string;
    /**
     * A longer description of this Action, usually describing what it does in more detail.
     * @type {string}
     * @memberof Action
     */
    'description': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof Action
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Action
     */
    'id': string;
    /**
     * The developer provided identifier for this Action.
     * @type {string}
     * @memberof Action
     */
    'key': string;
    /**
     * The type of this Action.
     * @type {string}
     * @memberof Action
     */
    'action_type': ActionActionTypeEnum;
    /**
     * 
     * @type {ActionApp}
     * @memberof Action
     */
    'app': ActionApp;
    /**
     * Will be set to `true` if this Action triggers instantly. May only be `true` when `type` is `READ`.
     * @type {boolean}
     * @memberof Action
     */
    'is_instant': boolean;
}

type ActionActionTypeEnum = 'READ' | 'WRITE'


