/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Action } from './action';
import { Links } from './links';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface ActionsListAvailableActionsResponse
 */
export interface ActionsListAvailableActionsResponse {
    /**
     * 
     * @type {Links}
     * @memberof ActionsListAvailableActionsResponse
     */
    'links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof ActionsListAvailableActionsResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Array<Action>}
     * @memberof ActionsListAvailableActionsResponse
     */
    'data'?: Array<Action>;
}

