/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { JSONError } from './jsonerror';

/**
 * 
 * @export
 * @interface ActionsListAvailableActions404Response
 */
export interface ActionsListAvailableActions404Response {
    /**
     * 
     * @type {Array<JSONError>}
     * @memberof ActionsListAvailableActions404Response
     */
    'errors'?: Array<JSONError>;
}

