/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InputsWithAuthenticationIdNoPage } from './inputs-with-authentication-id-no-page';

/**
 * 
 * @export
 * @interface ActionsTestActionExecutionRequest
 */
export interface ActionsTestActionExecutionRequest {
    /**
     * 
     * @type {InputsWithAuthenticationIdNoPage}
     * @memberof ActionsTestActionExecutionRequest
     */
    'data'?: InputsWithAuthenticationIdNoPage;
}

