/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ActionsGetInputFieldsResponseDataInner } from './actions-get-input-fields-response-data-inner';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface ActionsGetInputFieldsResponse
 */
export interface ActionsGetInputFieldsResponse {
    /**
     * 
     * @type {Meta}
     * @memberof ActionsGetInputFieldsResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Array<ActionsGetInputFieldsResponseDataInner>}
     * @memberof ActionsGetInputFieldsResponse
     */
    'data'?: Array<ActionsGetInputFieldsResponseDataInner>;
}

