/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Images/icons of various resolutions to represent the app.
 * @export
 * @interface AppImages
 */
export interface AppImages {
    /**
     * 
     * @type {string}
     * @memberof AppImages
     */
    'url_16x16'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppImages
     */
    'url_32x32'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppImages
     */
    'url_64x64'?: string;
    /**
     * 
     * @type {string}
     * @memberof AppImages
     */
    'url_128x128'?: string;
}

