/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface AppLinks
 */
export interface AppLinks {
    /**
     * A url that, when visited, will direct the user to authenticate with the app and allow Zapier access to the app, thus creating a new Authentication.  If value is `null`, then no authentication is required to use the app.
     * @type {any}
     * @memberof AppLinks
     */
    'connect_new_authentication'?: any;
}

