/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AppCategoriesInner } from './app-categories-inner';
import { AppImages } from './app-images';
import { AppLinks } from './app-links';

/**
 * An app that integrates with Zapier.
 * @export
 * @interface App
 */
export interface App {
    /**
     * Human readable name of the app
     * @type {string}
     * @memberof App
     */
    'title'?: string;
    /**
     * Human readable description of the app.
     * @type {string}
     * @memberof App
     */
    'description'?: string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof App
     */
    'type': string;
    /**
     * Unique id of the app
     * @type {string}
     * @memberof App
     */
    'id': string;
    /**
     * A list of categories to which this app belongs. Helpful in identifying apps by type and functionality.
     * @type {Array<AppCategoriesInner>}
     * @memberof App
     */
    'categories'?: Array<AppCategoriesInner>;
    /**
     * A branded color that can be used to represent the app.
     * @type {string}
     * @memberof App
     */
    'hex_color'?: string;
    /**
     * Default image/icon to represent the app.
     * @type {string}
     * @memberof App
     */
    'image'?: string;
    /**
     * 
     * @type {AppImages}
     * @memberof App
     */
    'images'?: AppImages;
    /**
     * 
     * @type {AppLinks}
     * @memberof App
     */
    'links'?: AppLinks;
}

