/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { App } from './app';
import { Links } from './links';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface AppsListPopularResponse
 */
export interface AppsListPopularResponse {
    /**
     * 
     * @type {Links}
     * @memberof AppsListPopularResponse
     */
    'links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof AppsListPopularResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Array<App>}
     * @memberof AppsListPopularResponse
     */
    'data'?: Array<App>;
}

