/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticationApp } from './authentication-app';

/**
 * An Authentication contains various fields, often credentials such as API tokens, used to access Partner APIs on behalf of a user. The actual fields are held securely by Zapier.
 * @export
 * @interface Authentication
 */
export interface Authentication {
    /**
     * 
     * @type {string}
     * @memberof Authentication
     */
    'title': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof Authentication
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Authentication
     */
    'id': string;
    /**
     * 
     * @type {AuthenticationApp}
     * @memberof Authentication
     */
    'app': AuthenticationApp;
    /**
     * If `true`, this Authentication has expired. It will not be usable, and the user needs to be directed to reconnect it.
     * @type {boolean}
     * @memberof Authentication
     */
    'is_expired': boolean;
}

