/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Authentication } from './authentication';
import { Links } from './links';
import { Meta } from './meta';

/**
 * 
 * @export
 * @interface AuthenticationsCreateNewAuthenticationResponse
 */
export interface AuthenticationsCreateNewAuthenticationResponse {
    /**
     * 
     * @type {Links}
     * @memberof AuthenticationsCreateNewAuthenticationResponse
     */
    'links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof AuthenticationsCreateNewAuthenticationResponse
     */
    'meta'?: Meta;
    /**
     * 
     * @type {Array<Authentication>}
     * @memberof AuthenticationsCreateNewAuthenticationResponse
     */
    'data'?: Array<Authentication>;
}

