/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { App } from './app';
import { AppCategoriesInner } from './app-categories-inner';
import { AppImages } from './app-images';
import { AppLinks } from './app-links';

/**
 * @type AuthenticationApp
 * @export
 */
export type AuthenticationApp = App | string;


