/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AuthenticationsCreateNewAuthenticationRequestData } from './authentications-create-new-authentication-request-data';

/**
 * 
 * @export
 * @interface AuthenticationsCreateNewAuthenticationRequest
 */
export interface AuthenticationsCreateNewAuthenticationRequest {
    /**
     * 
     * @type {AuthenticationsCreateNewAuthenticationRequestData}
     * @memberof AuthenticationsCreateNewAuthenticationRequest
     */
    'data'?: AuthenticationsCreateNewAuthenticationRequestData;
}

