/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A single element from a set of Choices, variants in an enumeration. For example, selecting a country of residence in a dropdown of many available countries.
 * @export
 * @interface Choice
 */
export interface Choice {
    /**
     * The type of this object.
     * @type {string}
     * @memberof Choice
     */
    'type': string;
    /**
     * The ID of this variant.
     * @type {string}
     * @memberof Choice
     */
    'id': string;
    /**
     * An optional human-readable label for this variant. Useful if the actual value is not a human-readable value, such as an identifier.
     * @type {string}
     * @memberof Choice
     */
    'label'?: string;
    /**
     * The value of this variant.
     * @type {string}
     * @memberof Choice
     */
    'value': string;
}

