/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Links } from './links';
import { Meta } from './meta';
import { ZapRun } from './zap-run';

/**
 * 
 * @export
 * @interface ExperimentalGetZapRunsResponse
 */
export interface ExperimentalGetZapRunsResponse {
    /**
     * The list of Zap Runs.
     * @type {Array<ZapRun>}
     * @memberof ExperimentalGetZapRunsResponse
     */
    'data'?: Array<ZapRun>;
    /**
     * 
     * @type {Links}
     * @memberof ExperimentalGetZapRunsResponse
     */
    'links'?: Links;
    /**
     * 
     * @type {Meta}
     * @memberof ExperimentalGetZapRunsResponse
     */
    'Meta'?: Meta;
}

