/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InfoField } from './info-field';
import { InputField } from './input-field';
import { InputFieldItems } from './input-field-items';

/**
 * @type FieldsetFieldsInner
 * @export
 */
export type FieldsetFieldsInner = InputField | InfoField;


