/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { FieldsetFieldsInner } from './fieldset-fields-inner';

/**
 * A grouping of Input Fields and Info Fields. Usually displayed together under the provided heading.
 * @export
 * @interface Fieldset
 */
export interface Fieldset {
    /**
     * The human readable title for this group of fields.
     * @type {string}
     * @memberof Fieldset
     */
    'title': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof Fieldset
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof Fieldset
     */
    'id': string;
    /**
     * 
     * @type {Array<FieldsetFieldsInner>}
     * @memberof Fieldset
     */
    'fields': Array<FieldsetFieldsInner>;
}

