/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A field that is intended to display some useful information to the user. Often some longer form direction on how to configure further Input Fields, or restrictions imposed by the third party API.
 * @export
 * @interface InfoField
 */
export interface InfoField {
    /**
     * A markdown formatted piece of text that provides helpful information to the user.
     * @type {string}
     * @memberof InfoField
     */
    'description': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof InfoField
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof InfoField
     */
    'id': string;
}

