/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InputFieldItems
 */
export interface InputFieldItems {
    /**
     * Only set when `type` is `ARRAY`. Specifies the `type` of the elements of the array.
     * @type {string}
     * @memberof InputFieldItems
     */
    'type'?: InputFieldItemsTypeEnum;
}

type InputFieldItemsTypeEnum = 'STRING' | 'NUMBER' | 'INTEGER' | 'BOOLEAN'


