/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface InputsWithAuthenticationIdNoPage
 */
export interface InputsWithAuthenticationIdNoPage {
    /**
     * An Authentication ID, as provided by the `/authentications` endpoint.
     * @type {any}
     * @memberof InputsWithAuthenticationIdNoPage
     */
    'authentication'?: any;
    /**
     * The current set of input fields in a JSON object, where each key is the `id` of an Input Field, and the corresponding value the current value of the field.
     * @type {object}
     * @memberof InputsWithAuthenticationIdNoPage
     */
    'inputs'?: object;
}

