/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The links object returned in paginated response bodies.
 * @export
 * @interface Links
 */
export interface Links {
    /**
     * The URL of the next page of paginated results.
     * @type {any}
     * @memberof Links
     */
    'next'?: any | null;
    /**
     * The URL of the previous page of paginated results.
     * @type {any}
     * @memberof Links
     */
    'prev'?: any | null;
}

