/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The meta object returned in paginated response bodies.
 * @export
 * @interface Meta
 */
export interface Meta {
    /**
     * The limit value used in the request.
     * @type {number}
     * @memberof Meta
     */
    'limit'?: number;
    /**
     * The offset value used in the request.
     * @type {number}
     * @memberof Meta
     */
    'offset'?: number;
    /**
     * The total number of objects in the collection represented by the endpoint.
     * @type {number}
     * @memberof Meta
     */
    'count'?: number;
}

