/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * The meta object returned in paginated response bodies, for results using cursor pagination.
 * @export
 * @interface MetaWithPage
 */
export interface MetaWithPage {
    /**
     * The page of results requested
     * @type {number}
     * @memberof MetaWithPage
     */
    'page'?: number;
}

