/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * A field that is an output from an Action, often fields returned from a call to a Partner API.
 * @export
 * @interface OutputField
 */
export interface OutputField {
    /**
     * The title of this Output Field
     * @type {string}
     * @memberof OutputField
     */
    'title': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof OutputField
     */
    'type': string;
    /**
     * 
     * @type {string}
     * @memberof OutputField
     */
    'id': string;
    /**
     * An optional sample of the data this Output Field might contain.
     * @type {string}
     * @memberof OutputField
     */
    'sample'?: string;
}

