/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ZapRunStep
 */
export interface ZapRunStep {
    /**
     * Represents the current state or progress of the Zap Run Step.
     * @type {string}
     * @memberof ZapRunStep
     */
    'status'?: ZapRunStepStatusEnum;
    /**
     * The specific time when the execution of the step in the Zap run began.
     * @type {string}
     * @memberof ZapRunStep
     */
    'start_time'?: string;
}

type ZapRunStepStatusEnum = 'delayed' | 'scheduled' | 'pending' | 'error' | 'halted' | 'throttled' | 'held' | 'filtered' | 'skipped' | 'success'


