/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ZapStepsInnerAction } from './zap-steps-inner-action';
import { ZapStepsInnerAuthentication } from './zap-steps-inner-authentication';

/**
 * 
 * @export
 * @interface ZapStepsInner
 */
export interface ZapStepsInner {
    /**
     * The custom title of a Zap Step. If a step has not been given a custom title by the user, then the value will be null.
     * @type {any}
     * @memberof ZapStepsInner
     */
    'title'?: any;
    /**
     * 
     * @type {ZapStepsInnerAction}
     * @memberof ZapStepsInner
     */
    'action': ZapStepsInnerAction;
    /**
     * 
     * @type {object}
     * @memberof ZapStepsInner
     */
    'inputs': object;
    /**
     * 
     * @type {ZapStepsInnerAuthentication}
     * @memberof ZapStepsInner
     */
    'authentication': ZapStepsInnerAuthentication;
}

