/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Action } from './action';
import { ActionApp } from './action-app';

/**
 * @type ZapStepsInnerAction
 * Expandable. The Action associated with this Zap step.
 * @export
 */
export type ZapStepsInnerAction = Action | string;


