/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { Authentication } from './authentication';
import { AuthenticationApp } from './authentication-app';

/**
 * @type ZapStepsInnerAuthentication
 * Expandable. The Authentication associated with this zap step.
 * @export
 */
export type ZapStepsInnerAuthentication = Authentication | any;


