/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ZapRunStep } from './zap-run-step';

/**
 * 
 * @export
 * @interface ZapRun
 */
export interface ZapRun {
    /**
     * Zap Run Identifier.
     * @type {string}
     * @memberof ZapRun
     */
    'id'?: string;
    /**
     * The specific time when the Zap Run was initiated.
     * @type {string}
     * @memberof ZapRun
     */
    'start_time'?: string;
    /**
     * The specific time when the Zap Run was finished.
     * @type {string}
     * @memberof ZapRun
     */
    'end_time'?: string;
    /**
     * Represents the current state or progress of the Zap Run
     * @type {string}
     * @memberof ZapRun
     */
    'status'?: ZapRunStatusEnum;
    /**
     * Refers to the name or title of the specific Zap that the run is associated with.
     * @type {string}
     * @memberof ZapRun
     */
    'zap_title'?: string;
    /**
     * The list of sequential actions or processes involved in the execution of the associated Zap run.
     * @type {Array<ZapRunStep>}
     * @memberof ZapRun
     */
    'steps'?: Array<ZapRunStep>;
    /**
     * The information about the data inputted into and logged out from a specific Zap Run during its execution.
     * @type {string}
     * @memberof ZapRun
     */
    'data_in'?: string;
    /**
     * The information logged out from a specific Zap Run during its execution.
     * @type {string}
     * @memberof ZapRun
     */
    'data_out'?: string;
}

type ZapRunStatusEnum = 'delayed' | 'scheduled' | 'pending' | 'error' | 'halted' | 'throttled' | 'held' | 'filtered' | 'skipped' | 'success'


