/*
Zapier Embed API

The Zapier Embed API.

The version of the OpenAPI document: 1.0.0
Contact: contact@zapier.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { ZapLinks } from './zap-links';
import { ZapStepsInner } from './zap-steps-inner';

/**
 * The definition of the Zap that will be created.
 * @export
 * @interface Zap
 */
export interface Zap {
    /**
     * The human readable name of the Zap.
     * @type {string}
     * @memberof Zap
     */
    'title': string;
    /**
     * The type of this object.
     * @type {string}
     * @memberof Zap
     */
    'type'?: string;
    /**
     * A unique identifier of the Zap.
     * @type {string}
     * @memberof Zap
     */
    'id'?: string;
    /**
     * Whether the Zap is enabled (running) or not.
     * @type {boolean}
     * @memberof Zap
     */
    'is_enabled'?: boolean;
    /**
     * The date/time at which this Zap last ran sucessfully. A null value indicates that a Zap has never run successfully.
     * @type {any}
     * @memberof Zap
     */
    'last_successful_run_date'?: any;
    /**
     * An ordered list of steps that define the logic of the Zap.
     * @type {Set<ZapStepsInner>}
     * @memberof Zap
     */
    'steps': Set<ZapStepsInner>;
    /**
     * 
     * @type {string}
     * @memberof Zap
     */
    'updated_at'?: string;
    /**
     * 
     * @type {ZapLinks}
     * @memberof Zap
     */
    'links'?: ZapLinks;
}

